In [1]:
import numpy
def arrays(arr):
    return numpy.array(arr[::-1], float)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)


1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
import numpy as np
a=np.array(list(map(int,input().split())))
a.shape=(3,3)
print(a)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy
n , m = input().split();
a = [];
for i in range(int(n)):
    my_array = input().split();
    a.append(my_array);
lis1 = numpy.array(a,int);
print(numpy.transpose(lis1))
print(lis1.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [6]:
import numpy as np
a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [2]:
import numpy
d = tuple(  map(int,(input().split())     ))

arr1 = numpy.zeros((d), dtype = int)
print(arr1)
    
arr2 = numpy.ones((d), dtype = int)
print(arr2)


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [3]:
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [4]:
import numpy as np
n,m = map(int,input().split())

a=np.zeros((n,m),int)
b=np.zeros((n,m),int)
for i in range(n):
  a[i]=np.array(input().split(),int)
for i in range(n):
  b[i]=np.array(input().split(),int)  

print(a+b)
print(a-b)
print(a*b)
print(np.array(a/b,int))
print(a%b)
print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [5]:
import numpy as np

np.set_printoptions(legacy='1.13')

a = np.array(input().split(),float)

print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [6]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2
1 2
3 4
24


In [7]:
import numpy as np

n, m = list(map(int, (input().split())))
a = np.array([list(map(int,(input().split()))) for i in range(int(n))])
print(np.max(np.min(a, axis = 1), axis = None))

4 2 
 2 5 
 3 7
 1 3 
 4 0
3


In [8]:
import numpy

N, M = map(int, input().strip().split())

my_array = numpy.array([ input().strip().split() for _ in range(N) ], int)

print(numpy.mean(my_array, axis = 1))
print(numpy.var(my_array, axis = 0))
print(round(numpy.std(my_array, axis = None),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [9]:
import numpy
a=int(input())

arr1=numpy.array([list(map(int,input().split())) for _ in range(a)])

arr2=numpy.array([list(map(int,input().split())) for _ in range(a)])

print(numpy.dot(arr1,arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [10]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


In [11]:
import numpy as np
a=list(map(float,input().split()))
x=int(input())
print (np.polyval(a, x))

1.1 2 3
0
3.0


In [12]:
import numpy
n=int(input())
a=numpy.array([input().split() for _ in range(n)],float)
numpy.set_printoptions(legacy='1.13') #important
print(numpy.linalg.det(a))

2
1.1 1.1
1.1 1.1
0.0
